services:
  web:
    build: .
    container_name: company-profile-ttc
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - npm_network

networks:
  npm_network:
    external: true
    name: nginx-proxy-manager_default
